### ISSUE TITLE
Create "Faq" section

### ISSUE THREAD

**Issue by prakhar-asaiya** [TCP-Tech/codeutsava-frontend#14]
We want to reproduce this design:

![image](https://user-images.githubusercontent.com/63089922/209916725-ec30137a-02f4-45ac-953a-ac780a998f91.png)

Figma link: [Link to Figma Design](https://www.figma.com/file/zjlj2tBFeXMkAjwJZpEpta/CODEUTSAVA-6.0?node-id=0%3A1&t=bWPrpKwRGYd5sJzp-0)

Steps to accomplish:

1. Pull the dev branch and create your new branch based upon this issue.
2. Create a new section folder 'section7' inside the src/sections.
3. Inside the 'section7' folder create two files: Section7.css and Section7.js
4. Place the necessary assets from figma to assets/images.
5. For naming css classes, follow this reference: [Section1.css](https://github.com/TCP-Tech/codeutsava-frontend/blob/dev/src/sections/section1/Section1.css)
6. We want absolute precision in the designs, so please refer to figma for styles.
7. The plus sign should be clickable, and on clicking the plus sign a dropdown should open which would contain answer for the question. For the time being, put any random words as the answer.

**Comment by virajchandra51** [comment]
Please assign me this issue

**Comment by sahil9001** [comment]
@virajchandra51 I'll assign you another issue. This issue is to be done by Rohit
