### ISSUE TITLE
Create "Speakers" Section

### ISSUE THREAD

**Issue by sahil9001** [TCP-Tech/codeutsava-frontend#8]
We want to reproduce this design:
**Note : Keep the background simple as of now, don't involve the image which is in the background.**
![Capture](https://user-images.githubusercontent.com/32628578/209510932-f0f9b8b5-577f-49bd-90b0-54956b7e9516.PNG)

Figma link: [Link to Figma Design](https://www.figma.com/file/zjlj2tBFeXMkAjwJZpEpta/CODEUTSAVA-6.0?node-id=0%3A1&t=bWPrpKwRGYd5sJzp-0)

Steps to accomplish:
1.  Pull the dev branch and create your new branch based upon this issue.
2.  Create a new section folder 'section4' inside the src/sections.
3.  Inside the 'section4' folder create two files: Section4.css and Section4.js
4.  Place the necessary assets from figma to assets/images.
5.  For naming css classes, follow this reference: [Section1.css](https://github.com/TCP-Tech/codeutsava-frontend/blob/dev/src/sections/section1/Section1.css)
6.  We want absolute precision in the designs, so please refer to figma for styles.

**Comment by shubhanshu-0** [comment]
🫡
